<?php
declare(strict_types=1);
require __DIR__.'/../config/database.php';
require __DIR__.'/../src/Core/Auth.php'; require __DIR__.'/../src/Core/Csrf.php';
require __DIR__.'/../src/Services/AuditService.php'; require __DIR__.'/../src/Services/CsvImportService.php'; require __DIR__.'/../src/Services/ImportService.php'; require __DIR__.'/../src/Services/AssetService.php';
Auth::start();
$r=$_GET['r']??(Auth::user()?'dashboard':'login');
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pageStart(string $title):void{?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> — HWinfo</title><link rel="stylesheet" href="assets/app.css"></head><body><?php}
function pageEnd():void{?></body></html><?php}
function layout(string $title,string $body):void{pageStart($title);?><div class="layout"><aside class="side"><h2>HWinfo</h2><p>پایش سخت‌افزار سازمان</p><a href="?r=dashboard">داشبورد</a><a href="?r=assets">تجهیزات</a><a href="?r=import">ورود CSV</a><a href="?r=personnel">پرسنل</a><a href="?r=audit">گزارش ممیزی</a><a href="?r=logout">خروج</a></aside><main class="main"><?=$body?></main></div><?php pageEnd();}
if($r==='logout'){Auth::logout();header('Location:?r=login');exit;}
if($r==='login'){if(Auth::user()){header('Location:?r=dashboard');exit;} if($_SERVER['REQUEST_METHOD']==='POST'){Csrf::check($_POST['_csrf']??null);if(Auth::login($_POST['username']??'',$_POST['password']??'')){header('Location:?r=dashboard');exit;}$err='نام کاربری یا رمز عبور صحیح نیست.';} pageStart('ورود');echo '<div style="max-width:420px;margin:10vh auto" class="card"><h1>ورود به HWinfo</h1>'.(!empty($err)?'<p style="color:#dc2626">'.e($err).'</p>':'').'<form method="post"><input type="hidden" name="_csrf" value="'.e(Csrf::token()).'"><p><input class="input" name="username" placeholder="نام کاربری"></p><p><input class="input" type="password" name="password" placeholder="رمز عبور"></p><button class="btn">ورود</button></form></div>';pageEnd();exit;}
Auth::requireLogin();
if($r==='import' && $_SERVER['REQUEST_METHOD']==='POST'){Auth::requireRole(['admin','expert']);Csrf::check($_POST['_csrf']??null);try{$f=$_FILES['csv']??null;if(!$f||$f['error']!==UPLOAD_ERR_OK)throw new RuntimeException('فایل نامعتبر است');if($f['size']>10*1024*1024)throw new RuntimeException('حداکثر حجم 10MB است');$sha=CsvImportService::hash($f['tmp_name']);$rows=CsvImportService::read($f['tmp_name']);$id=ImportService::import($rows,$sha);$msg="ورود با موفقیت انجام شد. Batch #{$id}";}catch(Throwable $x){$err=$x->getMessage();}}
if($r==='approve' || $r==='reject'){Auth::requireRole(['admin','expert','user']);Csrf::check($_POST['_csrf']??null);AssetService::setStatus((int)$_POST['id'],$r==='approve'?'approved':'rejected');header('Location:?r=assets');exit;}
if($r==='assign'){Auth::requireRole(['admin','expert']);Csrf::check($_POST['_csrf']??null);AssetService::assign((int)$_POST['id'],($_POST['personnel_id']??'')!==''?(int)$_POST['personnel_id']:null,$_POST['location']??null,$_POST['asset_number']??null);header('Location:?r=assets');exit;}
if($r==='personnel-search'){header('Content-Type:application/json; charset=utf-8');$q=trim($_GET['q']??'');$s=db()->prepare("SELECT id,full_name,personnel_code,department FROM personnel WHERE active=1 AND (full_name LIKE ? OR personnel_code LIKE ?) ORDER BY full_name LIMIT 20");$s->execute(["%$q%","%$q%"]);echo json_encode($s->fetchAll(),JSON_UNESCAPED_UNICODE);exit;}
if($r==='dashboard'){ $c=(int)db()->query("SELECT COUNT(*) FROM computers")->fetchColumn();$p=(int)db()->query("SELECT COUNT(*) FROM computers WHERE status='pending'")->fetchColumn();$a=(int)db()->query("SELECT COUNT(*) FROM computers WHERE status='approved'")->fetchColumn();$body='<div class="top"><h1>داشبورد</h1><span>نسخه e001.1.00.000-alpha1</span></div><div class="grid"><div class="card"><b>کل رایانه‌ها</b><h2>'.$c.'</h2></div><div class="card"><b>در انتظار تأیید</b><h2>'.$p.'</h2></div><div class="card"><b>تأیید شده</b><h2>'.$a.'</h2></div></div>';layout('داشبورد',$body);exit;}
if($r==='import'){Auth::requireRole(['admin','expert']);$body='<div class="card"><h1>ورود اطلاعات CSV</h1><p>'.e($msg??'').'</p><p style="color:#dc2626">'.e($err??'').'</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="'.e(Csrf::token()).'"><input class="input" type="file" name="csv" accept=".csv" required><br><br><button class="btn">اعتبارسنجی و ورود</button></form></div>';layout('ورود CSV',$body);exit;}
if($r==='assets'){$s=db()->query("SELECT c.*,p.full_name FROM computers c LEFT JOIN personnel p ON p.id=c.personnel_id ORDER BY c.id DESC LIMIT 200");$rows='';foreach($s as $x){$rows.='<tr><td>'.e($x['id']).'</td><td>'.e($x['computer_name']).'</td><td>'.e($x['manufacturer'].' '.$x['model']).'</td><td>'.e($x['full_name']??'-').'</td><td><span class="badge">'.e($x['status']).'</span></td><td><form style="display:inline" method="post" action="?r=approve"><input type="hidden" name="_csrf" value="'.e(Csrf::token()).'"><input type="hidden" name="id" value="'.$x['id'].'"><button class="btn">تأیید</button></form> <form style="display:inline" method="post" action="?r=reject"><input type="hidden" name="_csrf" value="'.e(Csrf::token()).'"><input type="hidden" name="id" value="'.$x['id'].'"><button class="btn red">رد</button></form></td></tr>';}$body='<div class="top"><h1>تجهیزات</h1><a class="btn" href="?r=import">ورود CSV</a></div><div class="card"><table><tr><th>#</th><th>نام سیستم</th><th>مدل</th><th>مالک</th><th>وضعیت</th><th>عملیات</th></tr>'.$rows.'</table></div>';layout('تجهیزات',$body);exit;}
if($r==='personnel'){ $rows='';foreach(db()->query("SELECT * FROM personnel ORDER BY full_name") as $x)$rows.='<tr><td>'.e($x['personnel_code']).'</td><td>'.e($x['full_name']).'</td><td>'.e($x['department']).'</td><td>'.($x['active']?'فعال':'غیرفعال').'</td></tr>';layout('پرسنل','<div class="card"><h1>پرسنل</h1><table><tr><th>کد</th><th>نام</th><th>واحد</th><th>وضعیت</th></tr>'.$rows.'</table></div>');exit;}
if($r==='audit'){Auth::requireRole(['admin','expert']);$rows='';foreach(db()->query("SELECT a.*,u.full_name FROM audit_logs a JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 200") as $x)$rows.='<tr><td>'.e($x['created_at']).'</td><td>'.e($x['full_name']).'</td><td>'.e($x['action']).'</td><td>'.e($x['entity'].'#'.$x['entity_id']).'</td><td>'.e($x['ip_address']).'</td></tr>';layout('ممیزی','<div class="card"><h1>گزارش ممیزی</h1><table><tr><th>زمان</th><th>کاربر</th><th>عملیات</th><th>موجودیت</th><th>IP</th></tr>'.$rows.'</table></div>');exit;}
http_response_code(404);echo '404';
